# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    allow: 
      - dependency-type: "production"
    commit-message:
      prefix: "Composer update"
      include: "scope"
      time: "03:00"
      timezone: "Europe/Paris"
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "monthly"
    allow: 
      - dependency-type: "production"
    commit-message:
      prefix: "docker update"
      include: "scope"
      time: "04:00"
      timezone: "Europe/Paris"
