<?php return array(
    'root' => array(
        'name' => 'webjet-cloud/webjet-cloud',
        'pretty_version' => '3.1.0',
        'version' => '3.1.0.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'gargron/fileupload' => array(
            'pretty_version' => 'v1.4.5',
            'version' => '1.4.5.0',
            'reference' => 'fd2b79c9b868b9987925e098f5562231e691ce7d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gargron/fileupload',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/libphonenumber-for-php' => array(
            'pretty_version' => '8.13.19',
            'version' => '8.13.19.0',
            'reference' => '7b60d1264ba806e68fb99b06e73e2ed07815689e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/libphonenumber-for-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/locale' => array(
            'pretty_version' => '2.4',
            'version' => '2.4.0.0',
            'reference' => 'a6b33dfc9e8949b7e28133c4628b29cd9f1850bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/locale',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/recaptcha' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'd59a801e98a4e9174814a6d71bbc268dff1202df',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/recaptcha',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'icamys/php-sitemap-generator' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => '236d8e7de28e9bb3ff028180ab9e3d0fe7c047b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../icamys/php-sitemap-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'joomla/string' => array(
            'pretty_version' => '1.4.6',
            'version' => '1.4.6.0',
            'reference' => '728ba9e39a8f1bd15b75ab878f57fa505184b8ab',
            'type' => 'joomla-package',
            'install_path' => __DIR__ . '/../joomla/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'joomla/utilities' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'f5d4fcf778abbbf1c099814297c87ef177e8b268',
            'type' => 'joomla-package',
            'install_path' => __DIR__ . '/../joomla/utilities',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.71',
            'version' => '1.3.71.0',
            'reference' => 'ae42a47d7fecc1fbb7277b2f2d84c37a33edc3b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.8.0',
            'version' => '6.8.0.0',
            'reference' => 'df16b615e371d81fb79e506277faea67a1be18f1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.28.0',
            'version' => '1.28.0.0',
            'reference' => '42292d99c55abe617799667f454222c54c60e229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'visualappeal/php-ssllabs-api' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '51d5d6fab1613620ca7f5c3f88ce4d9936716435',
            'type' => 'library',
            'install_path' => __DIR__ . '/../visualappeal/php-ssllabs-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webjet-cloud/webjet-cloud' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
