<?php return array(
    'root' => array(
        'name' => 'webjet-cloud/webjet-cloud',
        'pretty_version' => '2.2.2',
        'version' => '2.2.2.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'giggsey/libphonenumber-for-php' => array(
            'pretty_version' => '8.12.54',
            'version' => '8.12.54.0',
            'reference' => 'd0bad134ca7206d36784c2c5ec531ba4513efde7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/libphonenumber-for-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/locale' => array(
            'pretty_version' => '2.2',
            'version' => '2.2.0.0',
            'reference' => '9c1dca769253f6a3e81f9a5c167f53b6a54ab635',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/locale',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/recaptcha' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '614f25a9038be4f3f2da7cbfd778dc5b357d2419',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/recaptcha',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'icamys/php-sitemap-generator' => array(
            'pretty_version' => '4.4.1',
            'version' => '4.4.1.0',
            'reference' => 'a43e954b0c5a4fa47f4aac7a7c0ca46c2f1c2c24',
            'type' => 'library',
            'install_path' => __DIR__ . '/../icamys/php-sitemap-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'joomla/string' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'bcdb8d45ad3953bf3cfc2b9577288823cab381b9',
            'type' => 'joomla-package',
            'install_path' => __DIR__ . '/../joomla/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'joomla/utilities' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'ab1660fd22184700306b932c39410ba955dc82e1',
            'type' => 'joomla-package',
            'install_path' => __DIR__ . '/../joomla/utilities',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.69',
            'version' => '1.3.69.0',
            'reference' => 'a61c949cccd086808063611ef9698eabe42ef22f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.6.4',
            'version' => '6.6.4.0',
            'reference' => 'a94fdebaea6bd17f51be0c2373ab80d3d681269b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'reference' => '9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'visualappeal/php-ssllabs-api' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '51d5d6fab1613620ca7f5c3f88ce4d9936716435',
            'type' => 'library',
            'install_path' => __DIR__ . '/../visualappeal/php-ssllabs-api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webjet-cloud/webjet-cloud' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
