<?php return array(
    'root' => array(
        'name' => 'webjet-cloud/webjet-cloud',
        'pretty_version' => '3.3.0',
        'version' => '3.3.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'gargron/fileupload' => array(
            'pretty_version' => 'v1.4.5',
            'version' => '1.4.5.0',
            'reference' => 'fd2b79c9b868b9987925e098f5562231e691ce7d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gargron/fileupload',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/libphonenumber-for-php' => array(
            'pretty_version' => '8.13.40',
            'version' => '8.13.40.0',
            'reference' => '795e0b760e5c439b6fa1ffa787c1d90c2face1ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/libphonenumber-for-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/libphonenumber-for-php-lite' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.13.40',
            ),
        ),
        'giggsey/locale' => array(
            'pretty_version' => '2.6',
            'version' => '2.6.0.0',
            'reference' => '37874fa473131247c348059fb7b8985efc18b5ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/locale',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'google/recaptcha' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'd59a801e98a4e9174814a6d71bbc268dff1202df',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/recaptcha',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'icamys/php-sitemap-generator' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => '236d8e7de28e9bb3ff028180ab9e3d0fe7c047b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../icamys/php-sitemap-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'joomla/string' => array(
            'pretty_version' => '1.4.6',
            'version' => '1.4.6.0',
            'reference' => '728ba9e39a8f1bd15b75ab878f57fa505184b8ab',
            'type' => 'joomla-package',
            'install_path' => __DIR__ . '/../joomla/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'joomla/utilities' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'f5d4fcf778abbbf1c099814297c87ef177e8b268',
            'type' => 'joomla-package',
            'install_path' => __DIR__ . '/../joomla/utilities',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/minify' => array(
            'pretty_version' => '1.3.73',
            'version' => '1.3.73.0',
            'reference' => 'cb7a9297b4ab070909cefade30ee95054d4ae87a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matthiasmullie/path-converter' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'e7d13b2c7e2f2268e1424aaed02085518afa02d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matthiasmullie/path-converter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'reference' => '039de174cd9c17a8389754d3b877a2ed22743e18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stantabcorp/i18n' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => '5a28cef6378a7f4bb232ce1ac9657ba9ef84a330',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stantabcorp/i18n',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => 'fd22ab50000ef01661e2a31d850ebaa297f8e03c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webjet-cloud/webjet-cloud' => array(
            'pretty_version' => '3.3.0',
            'version' => '3.3.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
